priorityClassName: system-node-critical

ingressController:
  enabled: true

gatewayAPI:
  enabled: true

k8sNetworkPolicy:
  enabled: false

k8sClusterNetworkPolicy:
  enabled: false

kubeProxyReplacement: "true"

operator:
  replicas: 1
  priorityClassName: system-cluster-critical