apiVersion: v1
kind: Namespace
metadata:
  labels:
    {{- include "kube-state-metrics.labels" . | indent 4 }}
    pager.example.com/key: pagerduty-demo
  annotations:
    {{- include "kube-state-metrics.patchedAnnotations" . | indent 4 }}
  name: {{ template "kube-state-metrics.namespace" . }}