blockBuilder:
  replicas: 1

liveStore:
  replicas: 1

ingest:
  kafka:
    address: "kafka.kafka-ci.svc.cluster.local:9092"
    auto_create_topic_default_partitions: 1

traces:
  otlp:
    http:
      enabled: true
